---
# tasks file for configure_jenkins
- name: Check if jenkins.war exists
  stat:
    path: /opt/jenkins/jenkins.war
  register: jenkins_war

- name: Create /opt/jenkins
  file:
    dest: /opt/jenkins
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    state: directory
  
- name: Download jenkins.war
  get_url:
    dest: /opt/jenkins/
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
  notify: jenkins_tune
  when: jenkins_war.stat.exists == false

